import { PrismaClient } from "@prisma/client";
import { Pool, neonConfig } from "@neondatabase/serverless";
import { PrismaNeon } from "@prisma/adapter-neon";
import ws from "ws";

// For seeding, use direct connection (not pooled)
neonConfig.webSocketConstructor = ws;

const databaseUrl = process.env.DATABASE_URL!;
const pool = new Pool({ connectionString: databaseUrl });
const adapter = new PrismaNeon(pool);

const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 Seeding database...");

  // Clean up
  await prisma.userAchievement.deleteMany();
  await prisma.xPLog.deleteMany();
  await prisma.challengeAttempt.deleteMany();
  await prisma.dailyChallengeAssignment.deleteMany();
  await prisma.userSkill.deleteMany();
  await prisma.challenge.deleteMany();
  await prisma.achievement.deleteMany();
  await prisma.skill.deleteMany();
  await prisma.session.deleteMany();
  await prisma.account.deleteMany();
  await prisma.user.deleteMany();

  // Create admin user
  const admin = await prisma.user.create({
    data: {
      email: "admin@ai-trainer.dev",
      name: "Admin",
      role: "admin",
      xp: 2500,
      level: 5,
      streak: 12,
      maxStreak: 15,
      lastActiveAt: new Date(),
    },
  });

  // Create demo users
  const demoUsers = await Promise.all([
    prisma.user.create({
      data: { email: "ivan@demo.dev", name: "Иван Петров", role: "user", xp: 1800, level: 4, streak: 7, maxStreak: 10, lastActiveAt: new Date() },
    }),
    prisma.user.create({
      data: { email: "maria@demo.dev", name: "Мария Сидорова", role: "user", xp: 3200, level: 6, streak: 21, maxStreak: 21, lastActiveAt: new Date() },
    }),
    prisma.user.create({
      data: { email: "alex@demo.dev", name: "Алексей Козлов", role: "user", xp: 950, level: 3, streak: 3, maxStreak: 8, lastActiveAt: new Date() },
    }),
    prisma.user.create({
      data: { email: "elena@demo.dev", name: "Елена Новикова", role: "user", xp: 4200, level: 7, streak: 30, maxStreak: 30, lastActiveAt: new Date() },
    }),
    prisma.user.create({
      data: { email: "dmitry@demo.dev", name: "Дмитрий Волков", role: "user", xp: 600, level: 2, streak: 1, maxStreak: 5, lastActiveAt: new Date() },
    }),
  ]);

  // Create Skills
  const skills = await Promise.all([
    prisma.skill.create({ data: { name: "Prompt Engineering", slug: "prompt-engineering", description: "Искусство написания эффективных промптов для AI-моделей", icon: "✍️", category: "prompting", order: 1, requiredXp: 200 } }),
    prisma.skill.create({ data: { name: "AI Агенты", slug: "ai-agents", description: "Создание и настройка AI-агентов для автоматизации задач", icon: "🤖", category: "agents", order: 2, requiredXp: 300 } }),
    prisma.skill.create({ data: { name: "Cursor", slug: "cursor", description: "AI-ассистент для программирования в IDE", icon: "🖱️", category: "tools", order: 3, requiredXp: 250 } }),
    prisma.skill.create({ data: { name: "Claude Code", slug: "claude-code", description: "Использование Claude для написания и анализа кода", icon: "🧠", category: "tools", order: 4, requiredXp: 250 } }),
    prisma.skill.create({ data: { name: "OpenAI API", slug: "openai-api", description: "Интеграция OpenAI API в проекты", icon: "🔮", category: "tools", order: 5, requiredXp: 300 } }),
    prisma.skill.create({ data: { name: "MCP", slug: "mcp", description: "Model Context Protocol — подключение контекста к AI", icon: "🔌", category: "tools", order: 6, requiredXp: 200 } }),
    prisma.skill.create({ data: { name: "RAG", slug: "rag", description: "Retrieval-Augmented Generation для обогащения ответов AI", icon: "📚", category: "automation", order: 7, requiredXp: 300 } }),
    prisma.skill.create({ data: { name: "AI Code Review", slug: "ai-code-review", description: "Автоматический код-ревью с помощью AI", icon: "👀", category: "review", order: 8, requiredXp: 200 } }),
    prisma.skill.create({ data: { name: "AI Автоматизация", slug: "ai-automation", description: "Автоматизация рутинных задач с помощью AI", icon: "⚡", category: "automation", order: 9, requiredXp: 250 } }),
    prisma.skill.create({ data: { name: "AI для 1С", slug: "ai-for-1c", description: "Применение AI в разработке на платформе 1С:Предприятие", icon: "🖥️", category: "1c", order: 10, requiredXp: 300 } }),
  ]);

  // Create Achievements
  const achievements = await Promise.all([
    prisma.achievement.create({ data: { name: "Первый шаг", slug: "first-challenge", description: "Реши первую задачу", icon: "🎯", category: "challenges", requirement: '{"type":"challenges","count":1}', xpReward: 50 } }),
    prisma.achievement.create({ data: { name: "10 задач", slug: "10-challenges", description: "Реши 10 задач", icon: "🔥", category: "challenges", requirement: '{"type":"challenges","count":10}', xpReward: 200 } }),
    prisma.achievement.create({ data: { name: "50 задач", slug: "50-challenges", description: "Реши 50 задач", icon: "💎", category: "challenges", requirement: '{"type":"challenges","count":50}', xpReward: 500 } }),
    prisma.achievement.create({ data: { name: "Неделя огня", slug: "7-day-streak", description: "Поддержи серию 7 дней подряд", icon: "🔥", category: "streak", requirement: '{"type":"streak","count":7}', xpReward: 200 } }),
    prisma.achievement.create({ data: { name: "Месяц дисциплины", slug: "30-day-streak", description: "Поддержи серию 30 дней подряд", icon: "👑", category: "streak", requirement: '{"type":"streak","count":30}', xpReward: 1000 } }),
    prisma.achievement.create({ data: { name: "Мастер промптов", slug: "prompt-master", description: "Достигни 5 уровня в Prompt Engineering", icon: "✍️", category: "skills", requirement: '{"type":"skill_level","skill":"prompt-engineering","level":5}', xpReward: 300 } }),
    prisma.achievement.create({ data: { name: "Создатель агентов", slug: "agent-builder", description: "Достигни 3 уровня в AI Агентах", icon: "🤖", category: "skills", requirement: '{"type":"skill_level","skill":"ai-agents","level":3}', xpReward: 200 } }),
    prisma.achievement.create({ data: { name: "Охотник за багами", slug: "bug-hunter", description: "Реши 5 задач по дебаггингу", icon: "🐛", category: "special", requirement: '{"type":"category_challenges","category":"debugging","count":5}', xpReward: 150 } }),
    prisma.achievement.create({ data: { name: "Детектор галлюцинаций", slug: "hallucination-detector", description: "Найди все ошибки в AI-генерированном коде", icon: "🕵️", category: "special", requirement: '{"type":"special","name":"hallucination"}', xpReward: 250 } }),
    prisma.achievement.create({ data: { name: "1С AI Эксперт", slug: "1c-ai-expert", description: "Достигни 5 уровня в AI для 1С", icon: "🏆", category: "special", requirement: '{"type":"skill_level","skill":"ai-for-1c","level":5}', xpReward: 500 } }),
    prisma.achievement.create({ data: { name: "Cursor мастер", slug: "cursor-master", description: "Достигни 3 уровня в навыке Cursor", icon: "🖱️", category: "skills", requirement: '{"type":"skill_level","skill":"cursor","level":3}', xpReward: 200 } }),
    prisma.achievement.create({ data: { name: "RAG специалист", slug: "rag-specialist", description: "Достигни 3 уровня в RAG", icon: "📚", category: "skills", requirement: '{"type":"skill_level","skill":"rag","level":3}', xpReward: 200 } }),
    prisma.achievement.create({ data: { name: "Автоматизатор", slug: "automator", description: "Достигни 3 уровня в AI Автоматизации", icon: "⚡", category: "skills", requirement: '{"type":"skill_level","skill":"ai-automation","level":3}', xpReward: 200 } }),
    prisma.achievement.create({ data: { name: "Ревьюер кода", slug: "code-reviewer", description: "Достигни 3 уровня в AI Code Review", icon: "👀", category: "skills", requirement: '{"type":"skill_level","skill":"ai-code-review","level":3}', xpReward: 200 } }),
    prisma.achievement.create({ data: { name: "MCP подключатель", slug: "mcp-connector", description: "Достигни 3 уровня в MCP", icon: "🔌", category: "skills", requirement: '{"type":"skill_level","skill":"mcp","level":3}', xpReward: 200 } }),
  ]);

  // Create Challenges (50+ in Russian)
  const challengesData = [
    // PROMPT ENGINEERING (10)
    {
      title: "Какой prompt лучше для генерации кода?",
      description: "Выбери наиболее эффективный промпт для генерации кода обработки 1С",
      difficulty: "easy",
      type: "multiple_choice",
      category: "prompting",
      xpReward: 25,
      content: JSON.stringify({ text: "Какой промпт даст лучший результат при генерации кода обработки 1С для массового обновления цен?" }),
      options: JSON.stringify([
        "Создай обработку для обновления цен номенклатуры через загрузку из Excel-файла с формой настройки",
        "Напиши код обработки 1С для пересчёта цен по процентной формуле с кнопкой запуска",
        "Сгенерируй обработку 1С 8.3 для массового обновления цен номенклатуры с формой выбора каталога и кнопкой выполнения",
        "Сделай внешнюю обработку для изменения цен по группе с отбором поставщика и журналом действий"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "Эффективный промпт содержит: платформу, конкретную задачу, описание формы и необходимых элементов. Чем детальнее — тем точнее результат.",
      validationType: "static",
      skillId: skills[0].id,
      order: 1,
    },
    {
      title: "Структура идеального промпта",
      description: "Определи правильную структуру промпта для AI",
      difficulty: "easy",
      type: "multiple_choice",
      category: "prompting",
      xpReward: 25,
      content: JSON.stringify({ text: "Какая структура промпта является наиболее эффективной?" }),
      options: JSON.stringify([
        "Пример → Контекст → Вопрос → Формат ответа",
        "Вопрос → Контекст → Формат ответа → Пример",
        "Контекст → Вопрос → Пример → Формат ответа",
        "Формат ответа → Пример → Контекст → Вопрос"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "Структура «Вопрос → Контекст → Формат → Пример» даёт AI максимум информации для точного ответа.",
      validationType: "static",
      skillId: skills[0].id,
      order: 2,
    },
    {
      title: "Исправь плохой промпт",
      description: "Улучши промпт для генерации отчёта в 1С",
      difficulty: "medium",
      type: "prompt_fix",
      category: "prompting",
      xpReward: 50,
      content: JSON.stringify({ text: "Улучши следующий промпт для генерации отчёта в 1С:", originalPrompt: "Сделай отчёт" }),
      options: null,
      correctAnswer: JSON.stringify("отчёт"),
      validationType: "pattern",
      validationConfig: JSON.stringify({ keywords: ["1С", "отчёт", "платформ", "8.3", "СКД", "форма", "период", "фильтр"] }),
      explanation: "Хороший промпт для отчёта 1С должен содержать: версию платформы, источник данных, поля вывода, фильтры и группировки, формат вывода (СКД/табличный документ).",
      hints: JSON.stringify(["Укажи платформу и версию", "Опиши какие данные нужны", "Укажи фильтры и группировки"]),
      skillId: skills[0].id,
      order: 3,
    },
    {
      title: "Few-shot prompting",
      description: "Как правильно использовать примеры в промпте",
      difficulty: "medium",
      type: "multiple_choice",
      category: "prompting",
      xpReward: 50,
      content: JSON.stringify({ text: "Что такое few-shot prompting и когда его лучше использовать?" }),
      options: JSON.stringify([
        "Повторение одного и того же промпта несколько раз для усиления эффекта запроса",
        "Использование нескольких AI-моделей одновременно для получения консенсусного ответа",
        "Техника составления коротких промптов из нескольких слов для ускорения генерации",
        "Предоставление нескольких примеров вход/выход в промпте для задания формата ответа"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "Few-shot prompting — это техника, когда в промпт включаются примеры желаемого формата ответа. Это особенно полезно для задач классификации, форматирования и генерации кода по шаблону.",
      validationType: "static",
      skillId: skills[0].id,
      order: 4,
    },
    {
      title: "Промпт для AI-агента анализа ТЗ",
      description: "Напиши промпт для AI-агента, который анализирует технические задания",
      difficulty: "hard",
      type: "prompt_fix",
      category: "prompting",
      xpReward: 100,
      content: JSON.stringify({ text: "Напиши системный промпт для AI-агента, который анализирует ТЗ на разработку 1С и выделяет: сущности, связи, требования к формам, ограничения", originalPrompt: "Анализируй ТЗ" }),
      options: null,
      correctAnswer: JSON.stringify("агент"),
      validationType: "pattern",
      validationConfig: JSON.stringify({ keywords: ["роль", "формат", "сущности", "связи", "требования", "ограничения", "1С"] }),
      explanation: "Системный промпт для агента должен определять: роль, контекст, формат ответа, конкретные задачи и ограничения. Чем структурированнее — тем лучше результат.",
      hints: JSON.stringify(["Определи роль AI-агента", "Задай структуру анализа", "Укажи формат выходных данных"]),
      skillId: skills[0].id,
      order: 5,
    },
    {
      title: "Chain of Thought промптинг",
      description: "Как заставить AI рассуждать пошагово",
      difficulty: "medium",
      type: "multiple_choice",
      category: "prompting",
      xpReward: 50,
      content: JSON.stringify({ text: "Какая фраза в промпте лучше всего активирует chain-of-thought рассуждение?" }),
      options: JSON.stringify([
        "Подумай пошагово",
        "Объясни подробно",
        "Реши по шагам",
        "Ответь детально"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "Фраза «Подумай пошагово» (Think step by step) активирует цепочку рассуждений, что значительно улучшает качество ответов на сложные задачи.",
      validationType: "static",
      skillId: skills[0].id,
      order: 6,
    },
    {
      title: "Температура модели",
      description: "Выбери правильную температуру для задачи",
      difficulty: "easy",
      type: "multiple_choice",
      category: "prompting",
      xpReward: 25,
      content: JSON.stringify({ text: "Какую температуру модели лучше выбрать для генерации кода обработки 1С?" }),
      options: JSON.stringify([
        "0.7 — для баланса точности и вариативности в ответах модели",
        "1.0 — стандартная температура для большинства задач генерации",
        "0 — для максимальной точности и детерминированности кода",
        "1.5 — для креативного подхода к написанию программного кода"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "Для генерации кода нужна температура 0 — максимальная детерминированность и точность. Креативность полезна для текстов, но не для кода.",
      validationType: "static",
      skillId: skills[0].id,
      order: 7,
    },
    {
      title: "Системный промпт vs Пользовательский",
      description: "В чём разница и когда использовать каждый",
      difficulty: "easy",
      type: "multiple_choice",
      category: "prompting",
      xpReward: 25,
      content: JSON.stringify({ text: "Какое утверждение о системном и пользовательском промптах верное?" }),
      options: JSON.stringify([
        "Системный промпт длиннее пользовательского и содержит больше деталей о задаче",
        "Системный задаёт поведение AI, пользовательский — конкретный запрос",
        "Системный промпт отправляется сервером, пользовательский — клиентским приложением",
        "Это одинаковые промпты с разными названиями, разница только в порядке отправки"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "Системный промпт (system prompt) задаёт роль, контекст и ограничения AI. Пользовательский (user prompt) — конкретный запрос в рамках заданного контекста.",
      validationType: "static",
      skillId: skills[0].id,
      order: 8,
    },
    {
      title: "Промпт-инъекция",
      description: "Как защитить промпт от злоумышленников",
      difficulty: "hard",
      type: "multiple_choice",
      category: "prompting",
      xpReward: 100,
      content: JSON.stringify({ text: "Что такое prompt injection и как от неё защититься?" }),
      options: JSON.stringify([
        "Ошибка в составлении промпта, приводящая к некорректному ответу; исправляется переписыванием",
        "Слишком длинный промпт, перегружающий контекстное окно модели; решается сокращением",
        "Использование чужого промпта без адаптации к своей задаче; решается кастомизацией",
        "Внедрение вредоносных инструкций в пользовательский ввод; защита — валидация и разделение контекстов"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "Prompt injection — это атака, когда в пользовательский ввод встраиваются инструкции, пытающиеся изменить поведение AI. Защита: валидация ввода, разделение системного и пользовательского контекста, санитизация.",
      validationType: "static",
      skillId: skills[0].id,
      order: 9,
    },
    {
      title: "Персона промпта",
      description: "Как правильно задать роль AI в промпте",
      difficulty: "medium",
      type: "text_input",
      category: "prompting",
      xpReward: 50,
      content: JSON.stringify({ text: "Напиши начало системного промпта, задающего роль Senior 1С-разработчика с 10-летним опытом", placeholder: "Ты — ..." }),
      options: null,
      correctAnswer: JSON.stringify("Ты — старший 1С-разработчик"),
      validationType: "pattern",
      validationConfig: JSON.stringify({ keywords: ["ты", "1с", "разработчик", "опыт", "старший", "senior"] }),
      explanation: "Задание роли через «Ты — ...» — один из самых эффективных способов улучшить качество ответов. Роль должна быть конкретной с указанием опыта и специализации.",
      hints: JSON.stringify(["Начни с 'Ты —'", "Укажи специализацию в 1С", "Добавь уровень опыта"]),
      skillId: skills[0].id,
      order: 10,
    },

    // AI AGENTS (6)
    {
      title: "Что такое AI-агент?",
      description: "Основные концепции AI-агентов",
      difficulty: "easy",
      type: "multiple_choice",
      category: "agents",
      xpReward: 25,
      content: JSON.stringify({ text: "Какое определение AI-агента наиболее точное?" }),
      options: JSON.stringify([
        "Интерактивный чат-бот с доступом к API внешних сервисов для обработки запросов",
        "Программный модуль на Python для автоматизации рутинных задач и скриптов",
        "Автономная система, воспринимающая среду и действующая для достижения целей",
        "Плагин для браузера, расширяющий возможности пользователя при работе с веб"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "AI-агент — это автономная система, которая воспринимает среду через датчики/входные данные и действует для достижения определённых целей, принимая решения без постоянного контроля человека.",
      validationType: "static",
      skillId: skills[1].id,
      order: 11,
    },
    {
      title: "Компоненты AI-агента",
      description: "Расставь компоненты AI-агента в правильном порядке",
      difficulty: "medium",
      type: "ordering",
      category: "agents",
      xpReward: 50,
      content: JSON.stringify({ text: "Расставь этапы работы AI-агента в правильном порядке:" }),
      options: JSON.stringify(["Восприятие среды", "Анализ и планирование", "Принятие решения", "Выполнение действия", "Оценка результата"]),
      correctAnswer: JSON.stringify([0, 1, 2, 3, 4]),
      explanation: "Цикл AI-агента: восприятие → анализ → решение → действие → оценка. Это называется perceive-reason-act циклом.",
      validationType: "static",
      skillId: skills[1].id,
      order: 12,
    },
    {
      title: "ReAct паттерн",
      description: "Как работает паттерн Reasoning + Acting",
      difficulty: "hard",
      type: "multiple_choice",
      category: "agents",
      xpReward: 100,
      content: JSON.stringify({ text: "В чём суть паттерна ReAct для AI-агентов?" }),
      options: JSON.stringify([
        "Параллельное выполнение нескольких задач агентом для ускорения обработки запросов",
        "Чередование рассуждений и действий с наблюдением результатов каждого шага",
        "Использование только рассуждений без реальных действий для планирования стратегии",
        "Быстрые автоматические реакции на входящие запросы без глубокого анализа контекста"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "ReAct (Reasoning + Acting) — это паттерн, при котором агент чередует рассуждения о задаче с конкретными действиями, наблюдая результат каждого шага и корректируя план.",
      validationType: "static",
      skillId: skills[1].id,
      order: 13,
    },
    {
      title: "Инструменты агента для 1С",
      description: "Какие инструменты нужны AI-агенту для работы с 1С",
      difficulty: "medium",
      type: "workflow_build",
      category: "agents",
      xpReward: 50,
      content: JSON.stringify({ text: "Собери pipeline AI-агента для автоматического код-ревью 1С:" }),
      options: JSON.stringify(["Получение кода из хранилища", "Парсинг и анализ метаданных 1С", "AI-анализ качества кода", "Генерация отчёта с рекомендациями", "Авто-исправление критичных проблем"]),
      correctAnswer: JSON.stringify([0, 1, 2, 3, 4]),
      explanation: "Полный pipeline: получение кода → парсинг метаданных → AI-анализ → генерация отчёта → авто-исправление. Каждый шаг использует результаты предыдущего.",
      validationType: "static",
      skillId: skills[1].id,
      order: 14,
    },
    {
      title: "Ограничения AI-агентов",
      description: "Что НЕ может AI-агент",
      difficulty: "medium",
      type: "multiple_choice",
      category: "agents",
      xpReward: 50,
      content: JSON.stringify({ text: "Какое ограничение AI-агентов является наиболее критичным при работе с 1С?" }),
      options: JSON.stringify([
        "Низкая скорость обработки запросов при работе с большими объёмами данных 1С",
        "Ограниченная поддержка русского языка в контексте бизнес-логики платформы",
        "Невозможность прямого взаимодействия с API-сервисами без промежуточных адаптеров",
        "Галлюцинации — генерация несуществующих методов и объектов 1С"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "Галлюцинации — главная проблема AI-агентов при работе с 1С. Модель может «придумать» несуществующие методы, объекты или свойства, что приведёт к неработающему коду.",
      validationType: "static",
      skillId: skills[1].id,
      order: 15,
    },
    {
      title: "Multi-agent система",
      description: "Когда использовать несколько агентов",
      difficulty: "hard",
      type: "multiple_choice",
      category: "agents",
      xpReward: 100,
      content: JSON.stringify({ text: "В каком сценарии multi-agent подход лучше одного агента?" }),
      options: JSON.stringify([
        "Когда задача требует разных экспертиз: аналитик + разработчик + тестировщик",
        "Когда нужно просто сгенерировать код по описанию задачи без дополнительного анализа",
        "Когда задача простая и не требует разделения на подзадачи и роли исполнителей",
        "Когда один агент работает медленно и нужно ускорить обработку параллельным запуском"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "Multi-agent системы эффективны, когда задача требует разных ролей и экспертиз. Каждый агент специализируется на своей области и результаты объединяются.",
      validationType: "static",
      skillId: skills[1].id,
      order: 16,
    },

    // CURSOR (5)
    {
      title: "Cursor: режимы работы",
      description: "Какие режимы Cursor эффективны для 1С",
      difficulty: "easy",
      type: "multiple_choice",
      category: "tools",
      xpReward: 25,
      content: JSON.stringify({ text: "Какой режим Cursor лучше всего подходит для рефакторинга большого модуля 1С?" }),
      options: JSON.stringify([
        "Chat — для быстрых вопросов и получения пояснений по фрагментам кода модуля",
        "Inline edit — для точечных мелких правок в отдельных строках исходного кода",
        "Composer — для комплексных изменений нескольких файлов при рефакторинге",
        "Terminal — для выполнения команд и запуска скриптов в командной строке"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "Composer (ранее Cmd+K multi-file) позволяет AI видеть контекст нескольких файлов и делать согласованные изменения — идеально для рефакторинга.",
      validationType: "static",
      skillId: skills[2].id,
      order: 17,
    },
    {
      title: "Cursor: контекст для 1С",
      description: "Как правильно предоставить контекст о проекте 1С",
      difficulty: "medium",
      type: "multiple_choice",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "Как лучше всего дать Cursor контекст о структуре конфигурации 1С?" }),
      options: JSON.stringify([
        "Описывать структуру проекта каждый раз вручную в чате при новом обращении к AI",
        "Добавить .cursorrules с описанием структуры конфигурации и стандартов кодирования",
        "Полагаться на встроенные знания AI о платформе 1С без дополнительных настроек",
        "Удалить все файлы проекта и создать их заново с полным описанием структуры"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "Файл .cursorrules позволяет задать постоянный контекст: стандарты кодирования, структура конфигурации, именование объектов, запрещённые паттерны.",
      validationType: "static",
      skillId: skills[2].id,
      order: 18,
    },
    {
      title: "Cursor: эффективный промпт",
      description: "Как писать запросы в Cursor для задач 1С",
      difficulty: "medium",
      type: "prompt_fix",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "Улучши промпт для Cursor при добавлении нового документа в конфигурацию 1С:", originalPrompt: "Добавь документ" }),
      options: null,
      correctAnswer: JSON.stringify("документ"),
      validationType: "pattern",
      validationConfig: JSON.stringify({ keywords: ["документ", "реквизиты", "табличная часть", "форма", "1С", "модуль"] }),
      explanation: "Эффективный промпт для Cursor: укажи тип объекта, реквизиты, табличные части, формы, поведения, модули. Чем детальнее — тем точнее результат.",
      hints: JSON.stringify(["Укажи тип документа", "Перечисли реквизиты", "Опиши табличные части"]),
      skillId: skills[2].id,
      order: 19,
    },
    {
      title: "Cursor: авто-комплит для 1С",
      description: "Как настроить Tab completion",
      difficulty: "easy",
      type: "multiple_choice",
      category: "tools",
      xpReward: 25,
      content: JSON.stringify({ text: "Что нужно сделать для улучшения Tab completion в Cursor при работе с 1С?" }),
      options: JSON.stringify([
        "Ничего дополнительно — Tab completion работает корректно сразу из коробки",
        "Отключить все AI-функции и перейти полностью на ручной ввод кода с клавиатуры",
        "Использовать только стандартные сниппеты без адаптации к специфике проекта 1С",
        "Включить Copilot++ и добавить примеры кода 1С в проект для обучения паттернам"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "Copilot++ (Cursor Tab) работает лучше, когда в проекте есть примеры кода — AI изучает паттерны и предлагает более точные автодополнения.",
      validationType: "static",
      skillId: skills[2].id,
      order: 20,
    },
    {
      title: "Cursor: @ symbols",
      description: "Как использовать @-ссылки в Cursor",
      difficulty: "medium",
      type: "multiple_choice",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "Какой @ символ в Cursor позволяет дать AI контекст из документации?" }),
      options: JSON.stringify([
        "@Docs — для подключения внешней документации как контекста для ответов AI",
        "@Files — для добавления файлов проекта в контекст текущего запроса к модели",
        "@Code — для ссылки на конкретные фрагменты кода в открытых файлах проекта",
        "@Git — для получения информации из истории коммитов и изменений в репозитории"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "@Docs позволяет подключить внешнюю документацию (например, docs.1c.ru или М ИТС) для контекстных ответов AI.",
      validationType: "static",
      skillId: skills[2].id,
      order: 21,
    },

    // CLAUDE CODE (4)
    {
      title: "Claude Code: установка и настройка",
      description: "Как начать работать с Claude Code",
      difficulty: "easy",
      type: "multiple_choice",
      category: "tools",
      xpReward: 25,
      content: JSON.stringify({ text: "Что такое Claude Code и как его запустить?" }),
      options: JSON.stringify([
        "Плагин для VS Code, добавляющий AI-ассистента в редактор для автодополнения кода",
        "Веб-сервис для взаимодействия с AI через браузер без локальной установки",
        "CLI-инструмент для AI-ассистента в терминале, запускается командой claude",
        "Мобильное приложение для общения с AI-ассистентом на смартфоне и планшете"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "Claude Code — это CLI-инструмент от Anthropic, который позволяет работать с AI прямо в терминале. Запускается командой 'claude' и понимает контекст проекта.",
      validationType: "static",
      skillId: skills[3].id,
      order: 22,
    },
    {
      title: "Claude Code: работа с проектом",
      description: "Как эффективно использовать Claude Code для задач 1С",
      difficulty: "medium",
      type: "prompt_fix",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "Улучши промпт для Claude Code при анализе медленного запроса 1С:", originalPrompt: "Запрос тормозит" }),
      options: null,
      correctAnswer: JSON.stringify("запрос"),
      validationType: "pattern",
      validationConfig: JSON.stringify({ keywords: ["запрос", "1С", "оптимизация", "индекс", "время", "профилирование"] }),
      explanation: "Для анализа производительности запроса укажи: текст запроса, объём данных, время выполнения, план запроса, индексы. Claude может предложить конкретные оптимизации.",
      hints: JSON.stringify(["Приложи текст запроса", "Укажи время выполнения", "Опиши объём данных"]),
      skillId: skills[3].id,
      order: 23,
    },
    {
      title: "Claude vs GPT для задач 1С",
      description: "Сравнение моделей для разных задач",
      difficulty: "medium",
      type: "multiple_choice",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "Для какой задачи Claude обычно показывает лучшие результаты, чем GPT?" }),
      options: JSON.stringify([
        "Быстрая генерация коротких функций и утилит с минимальным контекстом задачи",
        "Анализ и рефакторинг большого объёма кода благодаря большему контекстному окну",
        "Создание изображений и визуальных материалов по текстовому описанию задачи",
        "Работа с REST API и интеграция внешних сервисов в проекты на платформе 1С"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "Claude имеет преимущество в задачах, требующих анализа больших объёмов кода благодаря расширенному контекстному окну. GPT лучше для быстрых задач и API-интеграций.",
      validationType: "static",
      skillId: skills[3].id,
      order: 24,
    },
    {
      title: "Claude Code: CLAUDE.md",
      description: "Как настроить поведение Claude через CLAUDE.md",
      difficulty: "medium",
      type: "multiple_choice",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "Что такое файл CLAUDE.md в проекте?" }),
      options: JSON.stringify([
        "Конфигурационный файл базы данных для настройки подключения к источникам данных",
        "Файл логов с историей взаимодействий и запросов к AI-ассистенту в проекте",
        "Документация API с описанием эндпоинтов и форматов запросов к серверу",
        "Файл с инструкциями для Claude о поведении и стандартах проекта"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "CLAUDE.md — это файл с инструкциями для Claude Code, аналогичный .cursorrules. В нём задаётся контекст проекта, стандарты, предпочтения и ограничения.",
      validationType: "static",
      skillId: skills[3].id,
      order: 25,
    },

    // OPENAI API (5)
    {
      title: "OpenAI API: базовые концепции",
      description: "Как работает OpenAI API",
      difficulty: "easy",
      type: "multiple_choice",
      category: "tools",
      xpReward: 25,
      content: JSON.stringify({ text: "Какой эндпоинт OpenAI API используется для чат-комплитий?" }),
      options: JSON.stringify([
        "/v1/chat/completions — основной эндпоинт для чат-моделей GPT-4 и GPT-3.5",
        "/v1/completions — эндпоинт для генерации текста без поддержки системных сообщений",
        "/v1/generate — универсальный эндпоинт для генерации текста и изображений",
        "/v1/ask — упрощённый эндпоинт для вопросно-ответного формата взаимодействия"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "/v1/chat/completions — основной эндпоинт для чат-моделей (GPT-4, GPT-3.5). Он поддерживает системные и пользовательские сообщения.",
      validationType: "static",
      skillId: skills[4].id,
      order: 26,
    },
    {
      title: "OpenAI API: интеграция с 1С",
      description: "Как вызвать OpenAI API из 1С",
      difficulty: "hard",
      type: "ordering",
      category: "1c",
      xpReward: 100,
      content: JSON.stringify({ text: "Расставь шаги интеграции OpenAI API в обработку 1С в правильном порядке:" }),
      options: JSON.stringify(["Получить API-ключ OpenAI", "Создать HTTPСоединение с api.openai.com", "Сформировать JSON-тело запроса с промптом", "Отправить POST-запрос", "Обработать JSON-ответ и отобразить результат"]),
      correctAnswer: JSON.stringify([0, 1, 2, 3, 4]),
      explanation: "Последовательность: API-ключ → HTTP-соединение → JSON-запрос → POST → обработка ответа. В 1С используется HTTPСоединение и ЧтениеJSON/ЗаписьJSON.",
      validationType: "static",
      skillId: skills[4].id,
      order: 27,
    },
    {
      title: "OpenAI API: токены и лимиты",
      description: "Как рассчитать стоимость запросов",
      difficulty: "medium",
      type: "multiple_choice",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "Сколько примерно токенов содержит 1 страница текста на русском языке (4000 символов)?" }),
      options: JSON.stringify([
        "Около 500 токенов — кириллица токенизируется очень эффективно и компактно",
        "Около 10000 токенов — русский текст требует значительно больше токенов на символ",
        "Около 2000-3000 токенов — кириллица использует примерно 1.5-2 токена на символ",
        "Около 100 токенов — одна страница текста занимает минимум токенов контекста"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "Примерно 1 русский символ = 1.5-2 токена (кириллица токенизируется хуже). Страница 4000 символов ≈ 2000-3000 токенов. Это важно для расчёта стоимости и лимитов.",
      validationType: "static",
      skillId: skills[4].id,
      order: 28,
    },
    {
      title: "OpenAI: Function Calling",
      description: "Как использовать function calling для 1С",
      difficulty: "hard",
      type: "multiple_choice",
      category: "tools",
      xpReward: 100,
      content: JSON.stringify({ text: "Что такое Function Calling в OpenAI API и как его применить для 1С?" }),
      options: JSON.stringify([
        "Прямой вызов 1С-функций из API OpenAI без промежуточных слоёв и адаптеров",
        "Механизм, позволяющий модели вызывать функции; в 1С — для выполнения действий по текстовой команде",
        "Создание новых пользовательских функций в интерфейсе OpenAI для расширения API",
        "Плагин для VS Code, автоматически генерирующий вызовы функций на основе контекста"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "Function Calling позволяет модели определять, какую функцию нужно вызвать и с какими параметрами. В контексте 1С это даёт возможность AI-ассистенту выполнять действия: создавать документы, запускать обработки, формировать отчёты.",
      validationType: "static",
      skillId: skills[4].id,
      order: 29,
    },
    {
      title: "OpenAI: Streaming ответы",
      description: "Как реализовать streaming в 1С",
      difficulty: "hard",
      type: "multiple_choice",
      category: "1c",
      xpReward: 100,
      content: JSON.stringify({ text: "Как реализовать streaming ответ OpenAI API в обработке 1С?" }),
      options: JSON.stringify([
        "Дождаться полного ответа от API и отобразить результат целиком в форме обработки",
        "Использовать WebSocket-соединение для получения потоковых данных от OpenAI API",
        "Реализация streaming в 1С невозможна из-за ограничений платформы HTTP-запросов",
        "Использовать HTTPЗапрос с потоковым чтением ответа и постепенным отображением"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "Streaming возможен через HTTP-запрос с чтением ответа по частям. В 1С можно читать тело ответа порциями, парсить SSE-события и обновлять UI в реальном времени.",
      validationType: "static",
      skillId: skills[4].id,
      order: 30,
    },

    // MCP (4)
    {
      title: "MCP: что это и зачем",
      description: "Model Context Protocol — подключение контекста к AI",
      difficulty: "easy",
      type: "multiple_choice",
      category: "tools",
      xpReward: 25,
      content: JSON.stringify({ text: "Что такое MCP (Model Context Protocol)?" }),
      options: JSON.stringify([
        "Открытый протокол для подключения внешних данных и инструментов к AI-моделям",
        "Протокол обмена данными между компонентами платформы 1С в клиент-серверной архитектуре",
        "Язык программирования для описания контекста и метаданных в AI-приложениях",
        "Формат файла конфигурации для настройки параметров генерации текста моделью"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "MCP — это открытый протокол от Anthropic, который позволяет AI-моделям подключаться к внешним источникам данных и инструментам стандартизированным образом.",
      validationType: "static",
      skillId: skills[5].id,
      order: 31,
    },
    {
      title: "MCP серверы для 1С",
      description: "Какие MCP-серверы полезны для 1С разработки",
      difficulty: "medium",
      type: "multiple_choice",
      category: "1c",
      xpReward: 50,
      content: JSON.stringify({ text: "Какой MCP-сервер был бы наиболее полезен для 1С-разработчика?" }),
      options: JSON.stringify([
        "MCP-сервер для генерации и обработки изображений в документах 1С автоматически",
        "MCP-сервер для воспроизведения аудио и голосовых уведомлений в интерфейсе 1С",
        "MCP-сервер для доступа к метаданным конфигурации 1С через HTTP-сервисы",
        "MCP-сервер для работы с видеофайлами и стримингового контента в системе 1С"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "MCP-сервер для метаданных 1С позволяет AI видеть структуру конфигурации: справочники, документы, регистры — и генерировать более точный код.",
      validationType: "static",
      skillId: skills[5].id,
      order: 32,
    },
    {
      title: "MCP: архитектура",
      description: "Как работает MCP архитектура",
      difficulty: "medium",
      type: "ordering",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "Расставь компоненты архитектуры MCP в правильном порядке взаимодействия:" }),
      options: JSON.stringify(["AI-приложение (host)", "MCP-клиент внутри приложения", "MCP-сервер", "Внешний источник данных"]),
      correctAnswer: JSON.stringify([0, 1, 2, 3]),
      explanation: "Архитектура: Host (приложение) → MCP Client → MCP Server → Data Source. Каждый уровень отвечает за свою часть интеграции.",
      validationType: "static",
      skillId: skills[5].id,
      order: 33,
    },
    {
      title: "MCP: ресурсы и инструменты",
      description: "Разница между resources и tools в MCP",
      difficulty: "medium",
      type: "multiple_choice",
      category: "tools",
      xpReward: 50,
      content: JSON.stringify({ text: "В чём разница между Resources и Tools в MCP?" }),
      options: JSON.stringify([
        "Resources предназначены для изображений, а Tools — только для текстовых данных и команд",
        "Resources — данные для чтения (файлы, API), Tools — функции для выполнения действий",
        "Resources и Tools — это одно и то же с разными названиями для обратной совместимости",
        "Resources работают на серверной стороне, а Tools — исключительно на стороне клиента"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "Resources предоставляют данные для контекста (файлы, записи БД, API-ответы). Tools — это функции, которые AI может вызывать для выполнения действий (запросы, создание файлов).",
      validationType: "static",
      skillId: skills[5].id,
      order: 34,
    },

    // RAG (5)
    {
      title: "RAG: базовые принципы",
      description: "Retrieval-Augmented Generation — обогащение ответов AI",
      difficulty: "easy",
      type: "multiple_choice",
      category: "automation",
      xpReward: 25,
      content: JSON.stringify({ text: "Что такое RAG и какую проблему он решает?" }),
      options: JSON.stringify([
        "Метод сжатия данных для уменьшения объёма хранимой информации в базе знаний",
        "Система мониторинга производительности AI-моделей при обработке пользовательских запросов",
        "Фреймворк для автоматического тестирования ответов AI на соответствие спецификации",
        "Обогащение запросов к AI релевантным контекстом из базы знаний для уменьшения галлюцинаций"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "RAG (Retrieval-Augmented Generation) решает проблему галлюцинаций AI, обогащая промпт релевантной информацией из базы знаний перед генерацией ответа.",
      validationType: "static",
      skillId: skills[6].id,
      order: 35,
    },
    {
      title: "RAG: pipeline для 1С",
      description: "Собери RAG pipeline для базы знаний компании",
      difficulty: "hard",
      type: "workflow_build",
      category: "automation",
      xpReward: 100,
      content: JSON.stringify({ text: "Собери RAG pipeline для поиска решений в базе знаний компании на 1С:" }),
      options: JSON.stringify(["Загрузка документов в векторную БД", "Генерация эмбеддингов", "Векторный поиск по запросу", "Формирование промпта с найденным контекстом", "Генерация ответа AI"]),
      correctAnswer: JSON.stringify([0, 1, 2, 3, 4]),
      explanation: "RAG pipeline: загрузка → эмбеддинги → поиск → контекстуализация → генерация. Каждый шаг критичен для качества результата.",
      validationType: "static",
      skillId: skills[6].id,
      order: 36,
    },
    {
      title: "RAG: векторные базы",
      description: "Какую векторную БД выбрать",
      difficulty: "medium",
      type: "multiple_choice",
      category: "automation",
      xpReward: 50,
      content: JSON.stringify({ text: "Какую векторную базу данных лучше выбрать для RAG системы малого бизнеса на 1С?" }),
      options: JSON.stringify([
        "ChromaDB или Qdrant — открытые, лёгкие в настройке, бесплатные",
        "Pinecone — полностью облачное платное решение с масштабированием по подписке",
        "PostgreSQL с pgvector — надёжное решение для энтерпрайз-проектов с большой нагрузкой",
        "SQLite — простая локальная база, но не поддерживает векторный поиск и индексы"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "Для малого бизнеса ChromaDB или Qdrant — оптимальный выбор: открытый код, простая установка, достаточная производительность.",
      validationType: "static",
      skillId: skills[6].id,
      order: 37,
    },
    {
      title: "RAG: качество поиска",
      description: "Как улучшить релевантность результатов",
      difficulty: "hard",
      type: "multiple_choice",
      category: "automation",
      xpReward: 100,
      content: JSON.stringify({ text: "Какой метод лучше всего улучшает качество RAG поиска?" }),
      options: JSON.stringify([
        "Только векторный поиск по эмбеддингам для максимального семантического сходства",
        "Только полнотекстовый поиск по ключевым словам для точного совпадения терминов",
        "Hybrid search (векторный + лексический) с reranking результатов поиска",
        "Случайная выборка документов из базы знаний для обеспечения разнообразия контекста"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "Hybrid search комбинирует векторный поиск (семантическое сходство) с лексическим (ключевые слова) и применяет reranking для максимальной релевантности.",
      validationType: "static",
      skillId: skills[6].id,
      order: 38,
    },
    {
      title: "RAG: чанкинг документов",
      description: "Как правильно разбивать документы на части",
      difficulty: "medium",
      type: "multiple_choice",
      category: "automation",
      xpReward: 50,
      content: JSON.stringify({ text: "Какой размер чанка (фрагмента) оптимален для RAG системы с документацией 1С?" }),
      options: JSON.stringify([
        "1 токен — обеспечивает максимальную точность при поиске релевантных фрагментов",
        "512-1000 токенов с перекрытием 50-100 токенов для сохранения контекста",
        "10000 токенов — весь документ целиком для полной передачи контекста модели",
        "Размер чанка не имеет значения — качество поиска зависит только от модели"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "Оптимальный размер чанка: 512-1000 токенов с перекрытием. Слишком маленький — потеря контекста, слишком большой — шум в результатах поиска.",
      validationType: "static",
      skillId: skills[6].id,
      order: 39,
    },

    // AI CODE REVIEW (4)
    {
      title: "AI Code Review: зачем нужен",
      description: "Автоматический код-ревью с помощью AI",
      difficulty: "easy",
      type: "multiple_choice",
      category: "review",
      xpReward: 25,
      content: JSON.stringify({ text: "Какое преимущество AI-ревью по сравнению с ручным?" }),
      options: JSON.stringify([
        "AI всегда прав и не допускает ошибок при анализе кода в отличие от человека",
        "Разработчики больше не нужны — AI полностью заменяет ручной код-ревью в команде",
        "AI-ревью абсолютно бесплатно и не требует никаких затрат на инфраструктуру",
        "Мгновенный результат, покрытие всех файлов, последовательность проверок"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "AI-ревью не заменяет разработчиков, но дополняет: мгновенная обратная связь, покрытие всех файлов, постоянные критерии проверки.",
      validationType: "static",
      skillId: skills[7].id,
      order: 40,
    },
    {
      title: "Найди hallucination в коде",
      description: "AI сгенерировал код 1С с ошибками — найди их",
      difficulty: "medium",
      type: "multiple_choice",
      category: "debugging",
      xpReward: 50,
      content: JSON.stringify({ text: "AI предложил следующий код для запроса к регистру. В чём ошибка?\n\n```1c\nЗапрос = Новый Запрос;\nЗапрос.Текст = \"ВЫБРАТЬ Продажи.Контрагент, Продажи.СуммаДокумента ИЗ РегистрНакопления.Продажи\";\n```", code: "Запрос = Новый Запрос;\nЗапрос.Текст = \"ВЫБРАТЬ Продажи.Контрагент, Продажи.СуммаДокумента ИЗ РегистрНакопления.Продажи\";" }),
      options: JSON.stringify([
        "У регистра накопления нет поля «СуммаДокумента» — это галлюцинация AI",
        "Пропущена точка с запятой в конце оператора присвоения текста запроса",
        "Неправильно указан тип запроса — нужен запрос с параметрами и условиями",
        "Всё правильно — код не содержит ошибок и будет работать корректно"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "Регистр накопления «Продажи» имеет ресурсы (Сумма, Количество), но не «СуммаДокумента». AI «придумал» несуществующее поле — типичная галлюцинация.",
      validationType: "static",
      skillId: skills[7].id,
      order: 41,
    },
    {
      title: "AI Code Review: промпт для ревью",
      description: "Напиши эффективный промпт для AI-ревью кода 1С",
      difficulty: "hard",
      type: "prompt_fix",
      category: "review",
      xpReward: 100,
      content: JSON.stringify({ text: "Улучши промпт для AI-ревью модуля 1С:", originalPrompt: "Проверь код" }),
      options: null,
      correctAnswer: JSON.stringify("ревью"),
      validationType: "pattern",
      validationConfig: JSON.stringify({ keywords: ["1С", "ревью", "производительность", "безопасность", "качество", "стандарты", "лучшие практики"] }),
      explanation: "Эффективный промпт для ревью: укажи платформу, аспекты проверки (производительность, безопасность, чистота кода, стандарты 1С), формат отчёта.",
      hints: JSON.stringify(["Укажи платформу 1С", "Перечисли аспекты проверки", "Задай формат отчёта"]),
      skillId: skills[7].id,
      order: 42,
    },
    {
      title: "AI Code Review: автоматизация",
      description: "Как встроить AI-ревью в процесс разработки",
      difficulty: "hard",
      type: "workflow_build",
      category: "review",
      xpReward: 100,
      content: JSON.stringify({ text: "Собери pipeline автоматического AI-ревью для 1С:" }),
      options: JSON.stringify(["Девелопер коммитит код", "CI/CD извлекает изменённые модули", "AI анализирует код на ошибки и стандарты", "Формируется отчёт в PR", "Критичные проблемы автоматически исправляются"]),
      correctAnswer: JSON.stringify([0, 1, 2, 3, 4]),
      explanation: "Полный pipeline: коммит → извлечение изменений → AI-анализ → отчёт → авто-исправление. Это позволяет ловить проблемы до ручного ревью.",
      validationType: "static",
      skillId: skills[7].id,
      order: 43,
    },

    // AI AUTOMATION (3)
    {
      title: "AI для генерации тестов",
      description: "Автоматическая генерация тестов для 1С",
      difficulty: "medium",
      type: "multiple_choice",
      category: "automation",
      xpReward: 50,
      content: JSON.stringify({ text: "Какой подход к генерации тестов для 1С с помощью AI наиболее эффективен?" }),
      options: JSON.stringify([
        "Попросить AI написать тесты без предоставления контекста о коде и спецификации",
        "Сгенерировать только позитивные тесты для проверки счастливого пути выполнения",
        "Дать AI код модуля + спецификацию и попросить сгенерировать тесты по каждому методу",
        "Тесты для 1С не нужны — платформа обеспечивает достаточную надёжность без них"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "Наиболее эффективный подход: предоставить AI код + спецификацию, описать покрытие (позитивные, негативные, граничные случаи), задать фреймворк тестирования.",
      validationType: "static",
      skillId: skills[8].id,
      order: 44,
    },
    {
      title: "AI для документации 1С",
      description: "Автоматическая генерация документации",
      difficulty: "medium",
      type: "multiple_choice",
      category: "automation",
      xpReward: 50,
      content: JSON.stringify({ text: "Как AI может помочь в создании документации для конфигурации 1С?" }),
      options: JSON.stringify([
        "Полностью заменить технического писателя и генерировать готовую документацию без проверки",
        "Автоматически описать назначение объектов, методы API и бизнес-процессы по коду",
        "Сгенерировать только заголовки разделов без содержательного описания бизнес-логики",
        "Документация для 1С не нужна — код самодокументируемый и понятный без описания"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "AI может анализировать код и генерировать документацию: описание объектов, методов, параметров, бизнес-логики. Но требует проверки и дополнения человеком.",
      validationType: "static",
      skillId: skills[8].id,
      order: 45,
    },
    {
      title: "AI для миграции конфигурации",
      description: "Использование AI при миграции между версиями 1С",
      difficulty: "hard",
      type: "multiple_choice",
      category: "automation",
      xpReward: 100,
      content: JSON.stringify({ text: "Как AI может помочь при миграции конфигурации 1С на новую версию?" }),
      options: JSON.stringify([
        "Автоматически мигрировать всю конфигурацию без участия разработчика и проверки",
        "Полностью заменить ручное тестирование при переходе на новую версию платформы",
        "Удалить весь устаревший код и заменить его на актуальные реализации автоматически",
        "Проанализировать изменения в API и предложить адаптацию кода с учётом нового функционала"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "AI может: анализировать changelog, находить использование устаревших методов, предлагать адаптацию кода, генерировать скрипты миграции. Но финальная проверка — за разработчиком.",
      validationType: "static",
      skillId: skills[8].id,
      order: 46,
    },

    // AI FOR 1C (4)
    {
      title: "AI для генерации внешних обработок",
      description: "Как сгенерировать обработку 1С с помощью AI",
      difficulty: "medium",
      type: "prompt_fix",
      category: "1c",
      xpReward: 50,
      content: JSON.stringify({ text: "Улучши промпт для генерации внешней обработки 1С для выгрузки данных в Excel:", originalPrompt: "Сделай выгрузку в Excel" }),
      options: null,
      correctAnswer: JSON.stringify("обработка"),
      validationType: "pattern",
      validationConfig: JSON.stringify({ keywords: ["1С", "обработка", "Excel", "форма", "выгрузка", "8.3", "управляемое"] }),
      explanation: "Хороший промпт: укажи платформу (8.3, управляемое приложение), формат выгрузки, структуру данных, обработку ошибок, прогресс-бар.",
      hints: JSON.stringify(["Укажи платформу 1С", "Опиши структуру данных", "Укажи формат Excel"]),
      skillId: skills[9].id,
      order: 47,
    },
    {
      title: "Оптимизация запросов 1С с AI",
      description: "Как AI помогает оптимизировать запросы 1С",
      difficulty: "hard",
      type: "multiple_choice",
      category: "1c",
      xpReward: 100,
      content: JSON.stringify({ text: "AI проанализировал медленный запрос 1С. Какое предложение по оптимизации наиболее правильное?" }),
      options: JSON.stringify([
        "Заменить временные таблицы на виртуальные таблицы регистра и добавить индекс по полю фильтра",
        "Удалить все условия WHERE из запроса для упрощения логики и ускорения выполнения",
        "Увеличить таймаут запроса в настройках платформы, чтобы избежать ошибки превышения времени",
        "Использовать только СКД для всех запросов — система компоновки сама оптимизирует выполнение"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "Замена временных таблиц на виртуальные таблицы регистров и добавление индексов — наиболее эффективный способ оптимизации. AI может предложить и то, и другое, но нужно проверять рекомендации.",
      validationType: "static",
      skillId: skills[9].id,
      order: 48,
    },
    {
      title: "Интеграция 1С с REST API через AI",
      description: "Генерация кода интеграции с внешними сервисами",
      difficulty: "hard",
      type: "ordering",
      category: "1c",
      xpReward: 100,
      content: JSON.stringify({ text: "Расставь шаги интеграции 1С с REST API в правильном порядке:" }),
      options: JSON.stringify(["Определить API-эндпоинты и формат данных", "Создать HTTP-сервис в 1С или обработку", "Реализовать авторизацию (OAuth/API-key)", "Написать код обмена данными", "Добавить обработку ошибок и логирование"]),
      correctAnswer: JSON.stringify([0, 1, 2, 3, 4]),
      explanation: "Правильный порядок: изучение API → создание структуры → авторизация → обмен данными → обработка ошибок. Каждый шаг строится на предыдущем.",
      validationType: "static",
      skillId: skills[9].id,
      order: 49,
    },
    {
      title: "AI для анализа метаданных 1С",
      description: "Как использовать AI для анализа структуры конфигурации",
      difficulty: "medium",
      type: "multiple_choice",
      category: "1c",
      xpReward: 50,
      content: JSON.stringify({ text: "Какой формат выгрузки метаданных 1С лучше всего подходит для анализа AI?" }),
      options: JSON.stringify([
        "Скриншоты экрана конфигуратора с открытой структурой метаданных конфигурации",
        "Ручное текстовое описание структуры конфигурации, составленное разработчиком",
        "Выгрузка в .cf файл — бинарный формат, содержащий полную конфигурацию целиком",
        "Выгрузка конфигурации в файлы 1С:EDT — структурированный XML/JSON для анализа"
      ]),
      correctAnswer: JSON.stringify("3"),
      explanation: "Выгрузка в формате 1С:EDT даёт структурированные XML/JSON файлы с полным описанием метаданных — идеальный формат для анализа AI.",
      validationType: "static",
      skillId: skills[9].id,
      order: 50,
    },

    // DEBUGGING (4)
    {
      title: "Найди ошибку в AI-ответе",
      description: "AI сгенерировал код с ошибкой — найди её",
      difficulty: "medium",
      type: "multiple_choice",
      category: "debugging",
      xpReward: 50,
      content: JSON.stringify({ text: "AI предложил код для обхода справочника. В чём ошибка?\n\n```1c\nЗапрос = Новый Запрос;\nЗапрос.Текст = \"ВЫБРАТЬ Ссылка, Наименование ИЗ Справочник.Номенклатура\";\nВыборка = Запрос.Выполнить().Выбрать();\nПока Выборка.Следующий() Цикл\n  Сообщить(Выборка.Имя);\nКонецЦикла;\n```", code: "Запрос = Новый Запрос;\nЗапрос.Текст = \"ВЫБРАТЬ Ссылка, Наименование ИЗ Справочник.Номенклатура\";\nВыборка = Запрос.Выполнить().Выбрать();\nПока Выборка.Следующий() Цикл\n  Сообщить(Выборка.Имя);\nКонецЦикла;" }),
      options: JSON.stringify([
        "Пропущена точка с запятой в операторе вывода результата выборки на экран",
        "Неправильно указан тип запроса — нужно использовать прямой обход справочника",
        "Поле «Имя» не существует — правильно «Наименование», как в тексте запроса",
        "Всё правильно — код не содержит ошибок и будет корректно работать при выполнении"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "В запросе выбрано поле «Наименование», а в коде обращаемся к «Имя» — такого поля в выборке нет. Это типичная ошибка AI: смешение названий полей.",
      validationType: "static",
      skillId: skills[7].id,
      order: 51,
    },
    {
      title: "Дебаггинг AI-сгенерированного запроса",
      description: "Найди причину медленной работы запроса",
      difficulty: "hard",
      type: "multiple_choice",
      category: "debugging",
      xpReward: 100,
      content: JSON.stringify({ text: "AI сгенерировал запрос, который работает 30 секунд. В чём вероятная причина?\n\n```1c\nВЫБРАТЬ *\nИЗ РегистрНакопления.Продажи КАК Продажи\n  ЛЕВОЕ СОЕДИНЕНИЕ Справочник.Контрагенты КАК Контрагенты\n  ПО Продажи.Контрагент = Контрагенты.Ссылка\nГДЕ Продажи.Период МЕЖДУ &Начало И &Конец\n  И Контрагенты.Категория = &Категория\n```\n\nТаблица Продажи: 10 млн записей. Контрагенты: 50 000.", code: "ВЫБРАТЬ *\nИЗ РегистрНакопления.Продажи КАК Продажи\n  ЛЕВОЕ СОЕДИНЕНИЕ Справочник.Контрагенты КАК Контрагенты\n  ПО Продажи.Контрагент = Контрагенты.Ссылка\nГДЕ Продажи.Период МЕЖДУ &Начало И &Конец\n  И Контрагенты.Категория = &Категория" }),
      options: JSON.stringify([
        "Запрос составлен правильно, 30 секунд — нормальное время для такого объёма данных",
        "Фильтр по правой таблице LEFT JOIN превращает его во INNER JOIN, плюс нет индекса по Категории",
        "Проблема в использовании SELECT * — нужно перечислить только нужные поля явно",
        "Необходимо убрать все условия WHERE для ускорения выполнения запроса к регистру"
      ]),
      correctAnswer: JSON.stringify("1"),
      explanation: "Условие по правой таблице LEFT JOIN превращает его в INNER JOIN. Плюс отсутствие индекса по полю Категория. Нужно: перенести условие в ВГДЕ ССЫЛКА или добавить индекс.",
      validationType: "static",
      skillId: skills[7].id,
      order: 52,
    },
    {
      title: "Какой AI инструмент лучше для код-ревью?",
      description: "Сравнение AI-инструментов для ревью кода 1С",
      difficulty: "medium",
      type: "multiple_choice",
      category: "review",
      xpReward: 50,
      content: JSON.stringify({ text: "Какой инструмент лучше всего подходит для автоматического код-ревью 1С?" }),
      options: JSON.stringify([
        "Claude Code с CLAUDE.md + кастомными правилами 1С для структурированного анализа",
        "GitHub Copilot — обеспечивает автодополнение кода, но не предназначен для ревью",
        "ChatGPT веб-версия — удобна для разговоров, но не интегрирована в процесс разработки",
        "Любой AI-инструмент одинаково эффективен для ревью — выбор не имеет значения"
      ]),
      correctAnswer: JSON.stringify("0"),
      explanation: "Claude Code с CLAUDE.md позволяет задать контекст проекта и стандарты 1С, анализировать несколько файлов и давать структурированный отчёт с конкретными рекомендациями.",
      validationType: "static",
      skillId: skills[7].id,
      order: 53,
    },
    {
      title: "Обнаружение SQL-инъекции в 1С",
      description: "AI-генерированный код уязвим — найди уязвимость",
      difficulty: "hard",
      type: "multiple_choice",
      category: "debugging",
      xpReward: 100,
      content: JSON.stringify({ text: "AI сгенерировал код обработчика. В чём уязвимость?\n\n```1c\nЗапрос = Новый Запрос;\nЗапрос.Текст = \"ВЫБРАТЬ * ИЗ Справочник.Пользователи ГДЕ Логин = \\\"\" + Логин + \"\\\"\";\n```", code: "Запрос = Новый Запрос;\nЗапрос.Текст = \"ВЫБРАТЬ * ИЗ Справочник.Пользователи ГДЕ Логин = \\\"\" + Логин + \"\\\"\";" }),
      options: JSON.stringify([
        "Неправильно указан тип запроса — следует использовать объектный подход вместо запроса",
        "Отсутствует блок обработки ошибок при выполнении запроса к базе данных 1С",
        "SQL-инъекция: конкатенация строк вместо параметров запроса — нужно УстановитьПараметр",
        "Всё правильно — конкатенация строк в запросе безопасна в платформе 1С"
      ]),
      correctAnswer: JSON.stringify("2"),
      explanation: "Конкатенация строк в запросе — классическая SQL-инъекция. Правильно: Запрос.УстановитьПараметр(\"Логин\", Логин). AI часто генерирует такой код, если не указать в промпте требования безопасности.",
      validationType: "static",
      skillId: skills[7].id,
      order: 54,
    },
  ];

  const challenges = await Promise.all(
    challengesData.map((ch) => prisma.challenge.create({ data: ch }))
  );

  console.log(`✅ Created ${challenges.length} challenges`);
  console.log(`✅ Created ${skills.length} skills`);
  console.log(`✅ Created ${achievements.length} achievements`);
  console.log(`✅ Created ${demoUsers.length + 1} users (including admin)`);
  console.log("🎉 Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
